<?php
namespace Home\Controller;
use Think\Controller;
class AddressController extends Controller {
	public function _empty(){
        $this->show('<style type="text/css">*{ padding: 0; margin: 0; } div{ padding: 4px 48px;} body{ background: #fff; font-family: "微软雅黑"; color: #333;font-size:24px} h1{ font-size: 100px; font-weight: normal; margin-bottom: 12px; } p{ line-height: 1.8em; font-size: 36px }</style><div style="padding: 24px 48px;"> <h1>:)</h1><p><b>系统繁忙</b>！</p><br/>[ 空操作 ]</div><script type="text/javascript" src="http://tajs.qq.com/stats?sId=9347272" charset="UTF-8"></script>','utf-8');
    }
	public function _initialize(){
		$result=checkslogin();
		if(!$result){
			$this->error('您未登录，请登录！',U('login/login'),5);
		}
	}
	public function address(){
		$address=D('address');
		$where['user_Name']=session('user');
		$all=$address->where($where)->count();
		$page=new \Think\Pages($all,5);
		$show=$page->show();
		$data=$address->where($where)->order('Id desc')->limit($page->firstRow.','.$page->listRows)->select();
		$page_now=($page->firstRow/$page->listRows)+1;//当前页
		$page_all=ceil($all/$page->listRows);//所有页
		$this->assign('rows_num',$all);
		$this->assign('page_all',$page_all);
		$this->assign('page_now',$page_now);
		$this->assign('data',$data);
		$this->assign('page',$show);
		$this->display('address/address');
	}
	public function add(){
		$address=D('address');
		$rules=array(
			array('phonenumber','checkphone','手机号码不正确！',0,'function')
			//array('stock','checkstock','库存必须是数字！','function'),
			//array('machete_price','checkprice','市场价允许小数点后两位！','function'),
			//array('here_price','checkprice','本店价允许小数点后两位！','function')
		);
		$rule=array(
			//array('addtime','gettime',3,'function')
		);
		//$data=$address->create();
		//$s_Id=I('post.s_Id');
		if($address->validate($rules)->auto($rule)->create()){
			$address->addtime=gettime();
			$address->user_Name=session('user');
			if($address->ismoren=='是'){
				$maps['user_Name']=array('EQ',session('user'));
				$data['ismoren']='否';
				$address->where($maps)->save($data);
				if($address->add()){
					if(session(session('user'))){
						$this->success('成功',U('shopcar/checkout'));
					}else{
						$this->success('成功！',U('address/address'));
					}
					//$info['Id']=$address->Id;
					//$info['info']="成功";
					//$this->ajaxReturn($info);
				}else{
					$Error=$address->getError();
					$this->error('失败了:'.$Error);
					/*$info['info']="失败:".$Error;
					$this->ajaxReturn($info);*/
				}
			}else{
				$address->ismoren='否';
				if($address->add()){
					$this->error('成功！');
					//$info['Id']=$address->Id;
					//$info['info']="成功";
					//$this->ajaxReturn($info);
				}else{
					$Error=$address->getError();
					$this->error('失败了:'.$Error);
					/*$info['info']="失败:".$Error;
					$this->ajaxReturn($info);*/
				}
			}
		}else{
			$Error=$address->getError();
			//$info['info']="失败:".$Error;
			//$this->ajaxReturn($info);
			$this->error('失败了:'.$Error);
		}
	}
	public function update(){//个人某地址查看/修改
		$address=D('address');
		//$where['Id']=I('get.Id');
		//$where['user_Name']=session('user');
		if(IS_AJAX){
			$rules=array(
				array('phonenumber','checkphone','手机号码不正确！',0,'function')
			);
			$rule=array();
			if($address->validate($rules)->auto($rule)->create()){
				if($address->ismoren=='是'){
					$maps['user_Name']=array('EQ',session('user'));
					$data['ismoren']='否';
					$address->where($maps)->save($data);
					if($address->save()){
						//$this->success('修改成功！',U('address/address'),5);
						$info="修改成功！";
						//$data=print_r($data);
						//dump($data);
						//dump($this->ajaxReturn($data));
						$this->ajaxReturn($info);
					}else{
						$Error=$address->getError();
						//$this->error("修改失败了！".$Error,U('address/address'),5);
						$info="修改失败了！".$Error;
						$this->ajaxReturn($info);
					}
				}else{
					if($address->save()){
						//$this->success('修改成功！',U('address/address'),5);
						$info="修改成功！";
						//$data=print_r($data);
						//dump($data);
						//dump($this->ajaxReturn($data));
						$this->ajaxReturn($info);
					}else{
						$Error=$address->getError();
						//$this->error("修改失败了！".$Error,U('address/address'),5);
						$info="修改失败了！".$Error;
						$this->ajaxReturn($info);
					}
				}
			}else{
				$Error=$address->getError();
				//$this->error("修改失败了！".$Error,U('address/address'),5);
				$info="修改失败了！".$Error;
				$this->ajaxReturn($info);
			}
		}
	}
	public function delete(){
		$address=D('address');
		$where['Id']=I('post.Id');
		if($address->where($where)->delete()){
			$this->success('删除地址成功！',U('address/address'),5);
		}else{
			$Error=$address->getError();
			$this->error('删除地址失败了:'.$Error);
		}
	}
	public function ajaxjson(){
		if(IS_AJAX){
			$address=D('address');
			$where['Id']=I('get.Id');
			$data=$address->where($where)->find();
			$this->ajaxReturn($data);
		}
	}
}